/**
 * Search-term synonyms for the icon picker.
 *
 * Maps what a user *types* to fragments that appear in icon *names*, rather than
 * annotating each icon. That direction matters: an icon set is thousands of
 * entries (Arch ships 2352), so tagging every one is unmaintainable, while a few
 * dozen search terms cover most of what people actually type. It also stays
 * theme-agnostic — a fragment that matches nothing in the current set simply
 * yields no result.
 *
 * Fragments are matched against the lowercased icon name (whole name, a
 * hyphen-separated token, or a substring). Names here lean Tabler, since that is
 * what Arch ships, but plain-English fragments (`camera`, `trash`) work across
 * most icon sets.
 *
 * A theme can extend this per icon by adding `keywords` to its `icons.json`
 * entries; both sources are searched.
 */
export const ICON_SYNONYMS = Object.freeze({
  // --- Actions ---
  delete: ["trash"],
  remove: ["trash", "minus"],
  bin: ["trash"],
  add: ["plus"],
  new: ["plus", "sparkles"],
  create: ["plus", "pencil"],
  edit: ["pencil", "edit"],
  write: ["pencil", "edit"],
  save: ["device-floppy", "download"],
  copy: ["copy"],
  duplicate: ["copy"],
  clone: ["copy"],
  paste: ["clipboard"],
  cut: ["scissors"],
  undo: ["arrow-back-up", "history"],
  redo: ["arrow-forward-up"],
  history: ["history", "clock"],
  refresh: ["refresh", "reload", "rotate"],
  reload: ["refresh", "reload"],
  sync: ["refresh", "rotate", "reload"],
  search: ["search", "zoom"],
  find: ["search", "zoom"],
  magnify: ["zoom", "search"],
  filter: ["filter", "adjustments"],
  sort: ["sort", "arrows-sort"],
  share: ["share"],
  send: ["send"],
  download: ["download", "arrow-down"],
  upload: ["upload", "arrow-up"],
  print: ["printer"],
  scan: ["scan", "qrcode", "barcode"],
  close: ["x", "square-x"],
  cancel: ["ban", "circle-x"],
  confirm: ["check"],
  done: ["check", "circle-check"],
  complete: ["check", "circle-check"],
  tick: ["check"],
  select: ["check", "pointer"],

  // --- Media & files ---
  photo: ["photo", "camera"],
  picture: ["photo", "camera"],
  image: ["photo", "camera"],
  gallery: ["photo", "layout-grid"],
  camera: ["camera"],
  video: ["video", "movie", "player-play"],
  play: ["player-play"],
  pause: ["player-pause"],
  stop: ["player-stop"],
  music: ["music", "headphones", "volume"],
  audio: ["volume", "music", "headphones"],
  sound: ["volume", "music"],
  mute: ["volume-off", "volume-3"],
  mic: ["microphone"],
  microphone: ["microphone"],
  record: ["microphone", "circle"],
  file: ["file"],
  document: ["file", "notes"],
  doc: ["file"],
  pdf: ["file-type-pdf", "file"],
  folder: ["folder"],
  directory: ["folder"],
  attachment: ["paperclip"],
  attach: ["paperclip"],
  clip: ["paperclip"],

  // --- People & accounts ---
  user: ["user"],
  person: ["user"],
  profile: ["user"],
  account: ["user"],
  avatar: ["user"],
  people: ["users"],
  team: ["users"],
  group: ["users"],
  family: ["users", "mood-kid"],
  login: ["login"],
  signin: ["login"],
  logout: ["logout"],
  signout: ["logout"],
  exit: ["logout", "door"],

  // --- Communication ---
  email: ["mail", "inbox"],
  mail: ["mail", "inbox"],
  envelope: ["mail"],
  inbox: ["inbox", "mail"],
  message: ["message", "bubble"],
  chat: ["message", "bubble"],
  comment: ["message", "bubble"],
  talk: ["message", "bubble"],
  sms: ["message"],
  phone: ["phone", "device-mobile"],
  call: ["phone"],
  contact: ["address-book", "phone", "mail"],
  notification: ["bell"],
  bell: ["bell"],
  alarm: ["alarm", "bell"],
  reminder: ["bell", "alarm", "calendar"],

  // --- Commerce ---
  cart: ["shopping-cart"],
  basket: ["basket", "shopping-bag"],
  shop: ["shopping", "building-store"],
  store: ["building-store", "shopping"],
  buy: ["shopping-cart", "credit-card"],
  price: ["tag", "currency", "coin"],
  cost: ["currency", "coin", "cash"],
  pay: ["credit-card", "cash", "coin"],
  payment: ["credit-card", "cash"],
  money: ["currency", "coin", "cash", "wallet"],
  currency: ["currency", "coin"],
  card: ["credit-card"],
  wallet: ["wallet"],
  invoice: ["file-invoice", "receipt"],
  receipt: ["receipt"],
  discount: ["discount", "percentage", "tag"],
  sale: ["discount", "tag", "percentage"],
  offer: ["discount", "tag", "gift"],
  gift: ["gift"],
  delivery: ["truck", "package"],
  shipping: ["truck", "package"],
  package: ["package", "box"],
  parcel: ["package", "box"],

  // --- Navigation & layout ---
  home: ["home"],
  house: ["home"],
  menu: ["menu"],
  hamburger: ["menu"],
  nav: ["menu", "layout-navbar"],
  back: ["arrow-left", "chevron-left"],
  previous: ["arrow-left", "chevron-left"],
  prev: ["arrow-left", "chevron-left"],
  next: ["arrow-right", "chevron-right"],
  forward: ["arrow-right", "chevron-right"],
  up: ["arrow-up", "chevron-up"],
  down: ["arrow-down", "chevron-down"],
  expand: ["maximize", "arrows-maximize", "chevron-down"],
  collapse: ["minimize", "arrows-minimize", "chevron-up"],
  fullscreen: ["maximize", "arrows-maximize"],
  grid: ["grid", "layout-grid"],
  layout: ["layout"],
  list: ["list"],
  table: ["table"],
  dashboard: ["dashboard", "layout-dashboard", "gauge"],
  sidebar: ["layout-sidebar"],

  // --- Status & feedback ---
  warning: ["alert-triangle", "alert-circle"],
  alert: ["alert-triangle", "alert-circle", "bell"],
  caution: ["alert-triangle"],
  error: ["alert-circle", "circle-x", "exclamation"],
  danger: ["alert-triangle", "skull"],
  success: ["check", "circle-check"],
  info: ["info-circle", "info-square"],
  help: ["help", "question-mark", "lifebuoy"],
  question: ["question-mark", "help"],
  faq: ["help", "question-mark"],
  support: ["lifebuoy", "help", "headset"],

  // --- Security ---
  lock: ["lock"],
  unlock: ["lock-open"],
  secure: ["lock", "shield"],
  security: ["shield", "lock"],
  password: ["lock", "key", "password"],
  private: ["lock", "eye-off"],
  key: ["key"],
  shield: ["shield"],
  protect: ["shield", "lock"],

  // --- Visibility ---
  view: ["eye"],
  preview: ["eye"],
  show: ["eye"],
  visible: ["eye"],
  hide: ["eye-off"],
  hidden: ["eye-off"],
  invisible: ["eye-off"],

  // --- Time & place ---
  calendar: ["calendar"],
  date: ["calendar"],
  schedule: ["calendar", "clock"],
  event: ["calendar", "confetti"],
  clock: ["clock"],
  time: ["clock", "hourglass"],
  timer: ["hourglass", "clock"],
  location: ["map-pin", "map", "location"],
  place: ["map-pin", "map"],
  address: ["map-pin", "home", "address-book"],
  map: ["map"],
  pin: ["map-pin", "pin"],
  navigation: ["navigation", "compass"],
  compass: ["compass"],

  // --- Favourites & tagging ---
  favorite: ["star", "heart", "bookmark"],
  favourite: ["star", "heart", "bookmark"],
  star: ["star"],
  bookmark: ["bookmark"],
  like: ["heart", "thumb-up"],
  love: ["heart"],
  rating: ["star"],
  tag: ["tag", "hash"],
  label: ["tag"],
  flag: ["flag"],
  hash: ["hash"],

  // --- Data & dev ---
  chart: ["chart", "graph"],
  graph: ["chart", "graph"],
  analytics: ["chart", "graph", "report"],
  stats: ["chart", "graph"],
  statistics: ["chart", "graph"],
  report: ["report", "chart", "file-analytics"],
  database: ["database", "server"],
  db: ["database"],
  server: ["server", "database"],
  storage: ["database", "server", "box"],
  cloud: ["cloud"],
  code: ["code", "terminal", "braces"],
  dev: ["code", "terminal"],
  programming: ["code", "terminal"],
  terminal: ["terminal", "prompt"],
  bug: ["bug"],
  issue: ["bug", "alert-circle"],
  api: ["plug", "code"],
  plugin: ["plug", "puzzle"],
  extension: ["puzzle", "plug"],
  addon: ["puzzle", "plug"],

  // --- Devices & connectivity ---
  mobile: ["device-mobile"],
  smartphone: ["device-mobile"],
  tablet: ["device-tablet", "device-ipad"],
  desktop: ["device-desktop"],
  computer: ["device-desktop", "device-laptop"],
  pc: ["device-desktop"],
  monitor: ["device-desktop"],
  screen: ["device-desktop", "device-mobile"],
  laptop: ["device-laptop"],
  printer: ["printer"],
  wifi: ["wifi"],
  network: ["network", "wifi", "world"],
  internet: ["world", "wifi", "network"],
  connection: ["plug", "wifi", "link"],
  bluetooth: ["bluetooth"],
  battery: ["battery"],
  power: ["power", "bolt", "plug"],
  charge: ["battery", "bolt"],
  plug: ["plug"],
  electric: ["bolt", "plug"],

  // --- Links ---
  link: ["link", "external-link"],
  url: ["link", "world"],
  external: ["external-link"],
  website: ["world", "browser"],
  browser: ["browser", "world"],

  // --- Nature & weather ---
  weather: ["cloud", "sun", "temperature"],
  forecast: ["cloud", "sun"],
  sun: ["sun"],
  light: ["sun", "bulb"],
  day: ["sun"],
  moon: ["moon"],
  dark: ["moon"],
  night: ["moon"],
  rain: ["cloud-rain", "droplet"],
  snow: ["snowflake"],
  temperature: ["temperature"],
  thermometer: ["temperature"],
  water: ["droplet"],
  drop: ["droplet"],
  fire: ["flame"],
  hot: ["flame", "temperature"],
  eco: ["leaf", "recycle", "plant"],
  green: ["leaf", "plant"],
  nature: ["leaf", "tree", "plant"],
  plant: ["plant", "leaf"],
  tree: ["tree"],
  animal: ["paw", "dog", "cat"],
  pet: ["paw", "dog", "cat"],

  // --- Food & travel ---
  food: ["tools-kitchen", "chef-hat", "meat", "salad", "pizza"],
  restaurant: ["tools-kitchen", "chef-hat"],
  eat: ["tools-kitchen", "meat"],
  meal: ["tools-kitchen", "salad"],
  drink: ["glass", "cup", "beer"],
  coffee: ["coffee", "cup"],
  cafe: ["coffee", "cup"],
  car: ["car"],
  vehicle: ["car", "truck"],
  drive: ["car", "steering-wheel"],
  bike: ["bike"],
  bicycle: ["bike"],
  plane: ["plane"],
  flight: ["plane"],
  travel: ["plane", "luggage", "map"],
  airport: ["plane"],
  train: ["train"],
  bus: ["bus"],
  boat: ["ship", "sailboat"],
  ship: ["ship"],

  // --- Health, education, business ---
  health: ["heartbeat", "stethoscope", "first-aid"],
  medical: ["stethoscope", "first-aid", "medical"],
  doctor: ["stethoscope", "user-heart"],
  hospital: ["building-hospital", "first-aid"],
  medicine: ["pill", "vaccine"],
  pill: ["pill"],
  building: ["building"],
  office: ["building", "briefcase"],
  company: ["building", "briefcase"],
  business: ["briefcase", "building"],
  work: ["briefcase"],
  job: ["briefcase"],
  school: ["school", "book"],
  education: ["school", "book", "certificate"],
  learn: ["book", "school"],
  study: ["book", "school"],
  course: ["book", "certificate"],
  book: ["book", "notebook"],
  read: ["book", "eye"],
  library: ["books", "book"],

  // --- Design ---
  design: ["palette", "brush", "pencil"],
  color: ["palette", "color-swatch", "droplet"],
  colour: ["palette", "color-swatch"],
  palette: ["palette"],
  paint: ["brush", "palette", "bucket"],
  brush: ["brush"],
  theme: ["palette", "brush"],
  crop: ["crop"],
  resize: ["resize", "arrows-maximize"],
  zoom: ["zoom"],
  ruler: ["ruler"],
  layers: ["stack", "layers"],

  // --- Misc ---
  settings: ["settings", "adjustments"],
  preferences: ["settings", "adjustments"],
  config: ["settings", "adjustments"],
  configuration: ["settings"],
  gear: ["settings"],
  cog: ["settings"],
  tools: ["tool", "settings"],
  award: ["award", "trophy", "medal"],
  trophy: ["trophy"],
  badge: ["badge", "award"],
  prize: ["award", "trophy", "gift"],
  win: ["trophy", "award"],
  target: ["target", "focus"],
  goal: ["target", "flag"],
  aim: ["target", "crosshair"],
  rocket: ["rocket"],
  launch: ["rocket"],
  startup: ["rocket"],
  fast: ["bolt", "rocket", "gauge"],
  speed: ["gauge", "bolt"],
  performance: ["gauge", "chart"],
  idea: ["bulb"],
  tip: ["bulb", "info-circle"],
  lightbulb: ["bulb"],
  magic: ["wand", "sparkles"],
  ai: ["robot", "sparkles", "brain"],
  robot: ["robot"],
  brain: ["brain"],
  hand: ["hand", "pointer"],
  click: ["pointer", "hand-click"],
  touch: ["hand", "pointer"],
  tap: ["hand-click", "pointer"],
  cursor: ["pointer", "cursor"],
  quote: ["quote", "blockquote"],
  language: ["language", "world"],
  translate: ["language", "world"],
  globe: ["world"],
  world: ["world"],
  accessibility: ["accessible", "wheelchair"],
  wheelchair: ["wheelchair", "accessible"],
  legal: ["scale", "gavel"],
  law: ["gavel", "scale"],
  balance: ["scale"],
  calculator: ["calculator", "math"],
  math: ["math", "calculator"],
  percent: ["percentage"],
  crown: ["crown"],
  premium: ["crown", "star", "diamond"],
  pro: ["crown", "star"],
  vip: ["crown", "star"],
  recycle: ["recycle"],
  qr: ["qrcode"],
  barcode: ["barcode"],
  id: ["id", "license"],
  identity: ["id", "user"],
  signature: ["signature", "writing"],
  social: ["brand"],
  logo: ["brand"],
  brand: ["brand"],
});
